### ISSUE TITLE
Einheit löschen klappt nicht

### ISSUE THREAD

**Issue by sulf-jubla** [gcettuzz/chuchipirat#13]
Wenn man bereits eine Einheit angewählt hat bei einer Zutat kann diese nicht mehr komplett gelöscht werden, sprich auf "ohne Einheit" gesetzt werden. Man muss die gesamte Zutat nochmals löschen und neu erfassen.

**Comment by gcettuzz** [comment]
Hoi Sulf. Problem wurde behoben. Bitte kurz auf dem Mac prüfen.

**Comment by sulf-jubla** [comment]
geht immer noch nicht. wenn schon eine Einheit angewählt war und ich sie lösche mit dem Kreuz, taucht sie wieder auf, wenn ich in ein anderes Feld klicke
