### ISSUE TITLE
Upload von .jpg Bilder von Mac klappt nicht

### ISSUE THREAD

**Issue by sulf-jubla** [gcettuzz/chuchipirat#14]
Bei mir sind alle jpg-Dateien grau und können nicht zum Upload ausgewählt werden, auch wenn das Rezept gespeichert ist. Es geht nur mit URL.

**Comment by gcettuzz** [comment]
Hoi Sulf. Problem wurde behoben. Bitte kurz prüfen.

**Comment by sulf-jubla** [comment]
es gehen nur jpeg dateiein, jpg gehen immer noch nicht
