### ISSUE TITLE
Feature-Request: Anpassung Prozess "Produkte erfassen"

### ISSUE THREAD

**Issue by Madeinzueri** [gcettuzz/chuchipirat#145]
Beim Klick auf '"*NeuesProdukt*" hinzufügen', soll erst eine Auflistung mit ähnlichen Produkten (sortiert nach Übereinstimmigkeit) erscheinen. Dadurch soll verhindert werden, dass doppelte Produkte erfasst werden.

Bsp.
Wird "Aha! Creme fraiche" hinzugefügt, wird in den Produkten nach "Aha!", "Creme" und "fraiche" gesucht. Das Resultat wird nach % am meisten Übereinstimmung gelistet.
"Creme fraiche, laktosefrei" würde dadurch relativ weit oben in der Liste erscheinen.

**Comment by Madeinzueri** [comment]
Ähnlich bei Rezepten. Bevor ein neues angelegt werden kann, kann dem user eine Übersicht ähnlicher, bereits vorhandenen Rezepte (anhand des Titels) angezeigt werden Soll trotzdem ein neues erstellt werden, muss dies bestätigt werden.

**Comment by Madeinzueri** [comment]
Issues:

- Spaces sollten ggf. auch berücksichtigt werden (das gleiche Produkt kann mit space vor, als auch nach der Artikelbezeichnung erstellt werden ohne, dass ein Vorschlag für die Übereinstimmung erscheint)
- ggf. sollte schon ein Wort (Regex: "^[a-zA-Z]+,") reichen für den trigger (Bsp.: "Beeren" und "Beeren, gekühlt" sind schon vorhanden, wird nun "Beeren, tiefgekühlt" erstellt, wird gefragt ob das Produkt bereits besteht) - klar so wird ein Schritt mehr notwendig um die meisten neuen Produkte zu erfassen, ich kann mir aber vorstellen, dass so weniger Redundanzen entstehen
- Wird versucht "Trauben" hinzuzufügen, erscheint eine Liste mit bestehenden Produkten, welche nichts mit Trauben gemein haben (ggf. auch bei anderen Produkten ein Problem)
- Seltsamen Verhalten: Versuche ich "Cranberries, roh" hinzuzufügen, wird mir "Randen, roh" vorgeschlagen. Versuche ich "Ajvar, roh" hinzuzufügen wird mir kein Vorschlag gemacht.

**Comment by gcettuzz** [comment]
Danke für die Rückmeldung. Zu deinen Punkten:

- Leerschläge werden bereits ignoriert.
- Um die Übereinstimmung zu prüfen wird der [Jaccard Index](https://w.wiki/A5A7) genutzt. Die ermöglicht es auch Tippfehler wie Mozarella (statt Mozzarella) zu identifizieren. Führt aber gleichzeitig dazu, dass Anagramme als gleich gekennzeichnet werden.
- Ich habe den Grenzwert für die Übereinstimmung von 0.7 auf 0.8 erhöht. Es sollten jetzt weniger Produkte erscheinen.

**Comment by gcettuzz** [comment]
Wurde bereits im Mai umgesetzt.
