### ISSUE TITLE
Feature-Request: "Produkt hinzufügen" als Schnellzugriff in Menüplan

### ISSUE THREAD

**Issue by chrisgwerder** [gcettuzz/chuchipirat#159]
Wir haben lange nicht bemerkt, dass einzelne Produkte in einem Menüplan auch direkt hinzugefügt werden können wie hier:
<img width="361" alt="image" src="https://github.com/user-attachments/assets/efd100dd-c6a8-4ffe-bfeb-e7570967f49c">

Stattdessen haben wir neue Rezepte erstellt mit einem Produkt drin.

Vorschlag: "Produkt hinzufügen" ebenfalls in einem Wochentag direkt anzeigen, z.B.:
![image](https://github.com/user-attachments/assets/ce9ffcfb-d85f-4a83-84af-357ab952620f)

**Comment by gcettuzz** [comment]
Hoi Christian
Danke für deinen Input. Das ist bewusst so gewählt. Wir wollen die Oberfläche nicht mit zu vielen Buttons übersäen. Unsere Usertests haben gezeigt, dass dies schlussendlich mehr für Verwirrung sorgt als unterstützt. Diese Funktion wäre im [Helpcenter](https://help.chuchipirat.ch/docs/event/menueplan/#produktematerial-hinzuf%C3%BCgen) beschrieben. Zudem ist sie mit nur einem Klick auf die 3 vertikalen Punkte schnell im Zugriff. Daher werden wir diesen Feature-Request nicht weiterverfolgen.
Trotzdem danke für deine aktive Beteiligung.

Beste Grüsse
Gio
